<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <NoWarn>NU1701</NoWarn>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <!-- Cần cho chụp màn hình đúng toạ độ trên màn hình có scale khác nhau -->
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="envdte" Version="17.13.40008" />
  </ItemGroup>

</Project>
